# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NaoGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(939, 707)
        self.gridLayoutWidget = QtGui.QWidget(MainWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 941, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.title_widget = QtGui.QWidget(self.gridLayoutWidget)
        self.title_widget.setObjectName(_fromUtf8("title_widget"))
        self.title_label = QtGui.QLabel(self.title_widget)
        self.title_label.setGeometry(QtCore.QRect(0, 0, 921, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.gridLayout.addWidget(self.title_widget, 0, 0, 1, 1)
        self.Userinfo_widget = QtGui.QWidget(MainWindow)
        self.Userinfo_widget.setGeometry(QtCore.QRect(10, 90, 621, 601))
        self.Userinfo_widget.setObjectName(_fromUtf8("Userinfo_widget"))
        self.user_info_label = QtGui.QLabel(self.Userinfo_widget)
        self.user_info_label.setGeometry(QtCore.QRect(200, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.user_info_label.setFont(font)
        self.user_info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.user_info_label.setObjectName(_fromUtf8("user_info_label"))
        self.line = QtGui.QFrame(self.Userinfo_widget)
        self.line.setGeometry(QtCore.QRect(10, 40, 601, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.current_sequence_label = QtGui.QLabel(self.Userinfo_widget)
        self.current_sequence_label.setGeometry(QtCore.QRect(30, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.current_sequence_label.setFont(font)
        self.current_sequence_label.setObjectName(_fromUtf8("current_sequence_label"))
        self.avg_reaction_time_label = QtGui.QLabel(self.Userinfo_widget)
        self.avg_reaction_time_label.setGeometry(QtCore.QRect(30, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.avg_reaction_time_label.setFont(font)
        self.avg_reaction_time_label.setObjectName(_fromUtf8("avg_reaction_time_label"))
        self.robot_feedback_label = QtGui.QLabel(self.Userinfo_widget)
        self.robot_feedback_label.setGeometry(QtCore.QRect(30, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.robot_feedback_label.setFont(font)
        self.robot_feedback_label.setObjectName(_fromUtf8("robot_feedback_label"))
        self.total_score_label = QtGui.QLabel(self.Userinfo_widget)
        self.total_score_label.setGeometry(QtCore.QRect(30, 160, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.total_score_label.setFont(font)
        self.total_score_label.setObjectName(_fromUtf8("total_score_label"))
        self.previous_score_label = QtGui.QLabel(self.Userinfo_widget)
        self.previous_score_label.setGeometry(QtCore.QRect(30, 190, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.previous_score_label.setFont(font)
        self.previous_score_label.setObjectName(_fromUtf8("previous_score_label"))
        self.line_3 = QtGui.QFrame(self.Userinfo_widget)
        self.line_3.setGeometry(QtCore.QRect(210, 70, 20, 141))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.performance_graph_label = QtGui.QLabel(self.Userinfo_widget)
        self.performance_graph_label.setGeometry(QtCore.QRect(70, 240, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.performance_graph_label.setFont(font)
        self.performance_graph_label.setObjectName(_fromUtf8("performance_graph_label"))
        self.performance_plot = KPlotWidget(self.Userinfo_widget)
        self.performance_plot.setGeometry(QtCore.QRect(10, 270, 291, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(11)
        self.performance_plot.setFont(font)
        self.performance_plot.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.performance_plot.setForegroundColor(QtGui.QColor(0, 0, 0))
        self.performance_plot.setObjectName(_fromUtf8("performance_plot"))
        self.performance_graph_label_2 = QtGui.QLabel(self.Userinfo_widget)
        self.performance_graph_label_2.setGeometry(QtCore.QRect(380, 240, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.performance_graph_label_2.setFont(font)
        self.performance_graph_label_2.setObjectName(_fromUtf8("performance_graph_label_2"))
        self.engagement_plot = KPlotWidget(self.Userinfo_widget)
        self.engagement_plot.setGeometry(QtCore.QRect(320, 270, 291, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(11)
        self.engagement_plot.setFont(font)
        self.engagement_plot.setAutoFillBackground(False)
        self.engagement_plot.setLineWidth(1)
        self.engagement_plot.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.engagement_plot.setForegroundColor(QtGui.QColor(0, 0, 0))
        self.engagement_plot.setObjectName(_fromUtf8("engagement_plot"))
        self.sequence_val = QtGui.QLabel(self.Userinfo_widget)
        self.sequence_val.setGeometry(QtCore.QRect(240, 70, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.sequence_val.setFont(font)
        self.sequence_val.setText(_fromUtf8(""))
        self.sequence_val.setObjectName(_fromUtf8("sequence_val"))
        self.avg_reaction_time_val = QtGui.QLabel(self.Userinfo_widget)
        self.avg_reaction_time_val.setGeometry(QtCore.QRect(240, 100, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.avg_reaction_time_val.setFont(font)
        self.avg_reaction_time_val.setText(_fromUtf8(""))
        self.avg_reaction_time_val.setObjectName(_fromUtf8("avg_reaction_time_val"))
        self.robot_feedback_val = QtGui.QLabel(self.Userinfo_widget)
        self.robot_feedback_val.setGeometry(QtCore.QRect(240, 130, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.robot_feedback_val.setFont(font)
        self.robot_feedback_val.setText(_fromUtf8(""))
        self.robot_feedback_val.setObjectName(_fromUtf8("robot_feedback_val"))
        self.total_score_val = QtGui.QLabel(self.Userinfo_widget)
        self.total_score_val.setGeometry(QtCore.QRect(240, 160, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.total_score_val.setFont(font)
        self.total_score_val.setText(_fromUtf8(""))
        self.total_score_val.setObjectName(_fromUtf8("total_score_val"))
        self.previous_score_val = QtGui.QLabel(self.Userinfo_widget)
        self.previous_score_val.setGeometry(QtCore.QRect(240, 190, 68, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(12)
        self.previous_score_val.setFont(font)
        self.previous_score_val.setText(_fromUtf8(""))
        self.previous_score_val.setObjectName(_fromUtf8("previous_score_val"))
        self.decision_widget = QtGui.QWidget(MainWindow)
        self.decision_widget.setGeometry(QtCore.QRect(650, 90, 271, 601))
        self.decision_widget.setObjectName(_fromUtf8("decision_widget"))
        self.decision_label = QtGui.QLabel(self.decision_widget)
        self.decision_label.setGeometry(QtCore.QRect(20, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.decision_label.setFont(font)
        self.decision_label.setAlignment(QtCore.Qt.AlignCenter)
        self.decision_label.setObjectName(_fromUtf8("decision_label"))
        self.line_2 = QtGui.QFrame(self.decision_widget)
        self.line_2.setGeometry(QtCore.QRect(10, 40, 251, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.start_button = QtGui.QPushButton(self.decision_widget)
        self.start_button.setGeometry(QtCore.QRect(80, 70, 111, 41))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.l3_button = QtGui.QPushButton(self.decision_widget)
        self.l3_button.setGeometry(QtCore.QRect(90, 160, 99, 27))
        self.l3_button.setObjectName(_fromUtf8("l3_button"))
        self.l5_button = QtGui.QPushButton(self.decision_widget)
        self.l5_button.setGeometry(QtCore.QRect(90, 190, 99, 27))
        self.l5_button.setObjectName(_fromUtf8("l5_button"))
        self.l7_button = QtGui.QPushButton(self.decision_widget)
        self.l7_button.setGeometry(QtCore.QRect(90, 220, 99, 27))
        self.l7_button.setObjectName(_fromUtf8("l7_button"))
        self.l9_button = QtGui.QPushButton(self.decision_widget)
        self.l9_button.setGeometry(QtCore.QRect(90, 250, 99, 27))
        self.l9_button.setObjectName(_fromUtf8("l9_button"))
        self.pos_feedback_button = QtGui.QPushButton(self.decision_widget)
        self.pos_feedback_button.setGeometry(QtCore.QRect(60, 280, 151, 27))
        self.pos_feedback_button.setObjectName(_fromUtf8("pos_feedback_button"))
        self.neg_feedback_button = QtGui.QPushButton(self.decision_widget)
        self.neg_feedback_button.setGeometry(QtCore.QRect(60, 310, 151, 27))
        self.neg_feedback_button.setObjectName(_fromUtf8("neg_feedback_button"))
        self.close_button = QtGui.QPushButton(self.decision_widget)
        self.close_button.setGeometry(QtCore.QRect(80, 480, 111, 41))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.connect_muse_button = QtGui.QPushButton(self.decision_widget)
        self.connect_muse_button.setGeometry(QtCore.QRect(60, 420, 151, 27))
        self.connect_muse_button.setObjectName(_fromUtf8("connect_muse_button"))
        self.gridLayoutWidget.raise_()
        self.Userinfo_widget.raise_()
        self.decision_widget.raise_()
        self.neg_feedback_button.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.close_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SequenceLearning", None))
        self.title_label.setText(_translate("MainWindow", "Sequence Learning - Admin Panel", None))
        self.user_info_label.setText(_translate("MainWindow", "User Information", None))
        self.current_sequence_label.setText(_translate("MainWindow", "Current Sequence", None))
        self.avg_reaction_time_label.setText(_translate("MainWindow", "Avg. Reaction Time", None))
        self.robot_feedback_label.setText(_translate("MainWindow", "Robot Feedback", None))
        self.total_score_label.setText(_translate("MainWindow", "Total Score", None))
        self.previous_score_label.setText(_translate("MainWindow", "Score - Previous Round", None))
        self.performance_graph_label.setText(_translate("MainWindow", "User Performance Graph", None))
        self.performance_graph_label_2.setText(_translate("MainWindow", "User Engagement", None))
        self.decision_label.setText(_translate("MainWindow", "Decision feedback", None))
        self.start_button.setText(_translate("MainWindow", "START", None))
        self.l3_button.setText(_translate("MainWindow", "L = 3", None))
        self.l5_button.setText(_translate("MainWindow", "L = 5", None))
        self.l7_button.setText(_translate("MainWindow", "L = 7", None))
        self.l9_button.setText(_translate("MainWindow", "L = 9", None))
        self.pos_feedback_button.setText(_translate("MainWindow", "Positive feedback", None))
        self.neg_feedback_button.setText(_translate("MainWindow", "Negative Feedback", None))
        self.close_button.setText(_translate("MainWindow", "CLOSE", None))
        self.connect_muse_button.setText(_translate("MainWindow", "Connect Muse", None))

from PyKDE4.kdeui import KPlotWidget
